// Sessions
export const SAVE_USER = 'SAVE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const FETCH_AUTH = 'FETCH_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SAVE_UPTOKEN = 'SAVE_UPTOKEN';
export const CLEAR_UPTOKEN = 'CLEAR_UPTOKEN';
export const LOADING_DATA = 'LOADING_DATA';
export const LOADED_DATA = 'LOADED_DATA';

export const LOADING_MODULE = 'LOADING_MODULE';
export const LOADED_MODULE = 'LOADED_MODULE';
export const LOADING_MODULE_ERROR = 'LOADING_MODULE_ERROR';

// Portals
export const ZOOMER_OPEN = 'ZOOMER_OPEN';
export const ZOOMER_CLOSE = 'ZOOMER_CLOSE';
export const UPDATE_LANG = 'UPDATE_LANG';
export const UPDATE_DIMENSION = 'UPDATE_DIMENSION';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const DIARY_OPEN = 'DIARY_OPEN';
export const DIARY_CLOSE = 'DIARY_CLOSE';
export const PHOTOSWIPE_OPEN = 'PHOTOSWIPE_OPEN';
export const PHOTOSWIPE_CLOSE = 'PHOTOSWIPE_CLOSE';
export const UPLOADER_START = 'UPLOADER_START';
export const UPLOADER_STOP = 'UPLOADER_STOP';
export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';

// SelectCounter
export const SELECT_COUNTER = 'SELECT_COUNTER';
export const SELECT_GROUP_COUNTER = 'SELECT_GROUP_COUNTER';
export const ENABLE_SELECT_ALL = 'ENABLE_SELECT_ALL';
export const DISABLE_SELECT_ALL = 'DISABLE_SELECT_ALL';
