import { SimpleSchema } from 'meteor/aldeed:simple-schema';

SimpleSchema.messages({
  required: '请输入 [label]',
  minString: '[label] 不能小于 [min] 个字符',
  maxString: '[label] 不能超过 [max] 个字符',
  minNumber: '[label] 不能小于 [min]',
  maxNumber: '[label] 不能超过 [max]',
  minDate: '[label] must be on or after [min]',
  maxDate: '[label] cannot be after [max]',
  badDate: '[label] 不是一个合法的日期',
  minCount: 'You must specify at least [minCount] values',
  maxCount: 'You cannot specify more than [maxCount] values',
  noDecimal: '[label] 必须是整数',
  notAllowed: '[value] is not an allowed value',
  expectedString: '[label] 必须是字符',
  expectedNumber: '[label] 必须是数字',
  expectedBoolean: '[label] must be a boolean',
  expectedArray: '[label] must be an array',
  expectedObject: '[label] must be an object',
  expectedConstructor: '[label] must be a [type]',
  regEx: [
    { msg: '[label] failed regular expression validation' },
    { exp: SimpleSchema.RegEx.Email, msg: '[label] 必须是一个合法的Email地址' },
    { exp: SimpleSchema.RegEx.WeakEmail, msg: '[label] 必须是一个合法的Email地址' },
    { exp: SimpleSchema.RegEx.Domain, msg: '[label] 必须是一个合法的域名地址' },
    { exp: SimpleSchema.RegEx.WeakDomain, msg: '[label] 必须是一个合法的域名地址' },
    { exp: SimpleSchema.RegEx.IP, msg: '[label] must be a valid IPv4 or IPv6 address' },
    { exp: SimpleSchema.RegEx.IPv4, msg: '[label] must be a valid IPv4 address' },
    { exp: SimpleSchema.RegEx.IPv6, msg: '[label] must be a valid IPv6 address' },
    { exp: SimpleSchema.RegEx.Url, msg: '[label] 必须是一个合法的URL地址' },
    { exp: SimpleSchema.RegEx.Id, msg: '[label] must be a valid alphanumeric ID' },
  ],
  keyNotInSchema: '[key] is not allowed by the schema',
});
